# Generated by Django 4.2.5 on 2023-10-02 09:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("device_management", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="devices",
            options={"verbose_name_plural": "Devices"},
        ),
    ]
